import {
  FaReact,
  FaAws,
  FaDocker,
  FaNodeJs,
  FaGithub,
  FaJava,
  FaPython,
  FaChartLine,
  FaCode,
  FaMicrochip,
  FaFileAlt,
  FaMicrophone,
  FaDatabase,
  FaMobileAlt,
  FaUniversalAccess,
  FaBrain,
  FaProjectDiagram,
  FaPlug,
  FaSyncAlt,
  FaStream,
  FaSitemap,
  FaShieldAlt,
  FaGlobe,
} from "react-icons/fa";
import {
  SiHtml5,
  SiCss,
  SiJavascript,
  SiNextdotjs,
  SiTailwindcss,
  SiMongodb,
  SiKubernetes,
  SiJenkins,
  SiRabbitmq,
  SiGrafana,
  SiPostman,
  SiHuggingface,
  SiExpress,
  SiSwagger,
  SiMysql,
  SiGithubactions,
  SiGit,
  SiCplusplus,
  SiC,
  SiTypescript,
  SiKotlin,
  SiFastapi,
  SiBun,
  SiApachemaven,
  SiSolidity,
  SiStripe,
  SiClerk,
  SiVite,
  SiFramer,
  SiReactrouter,
  SiRedis,
  SiSocketdotio,
  SiGooglegemini,
  SiSanity,
  SiGooglechrome,
  SiAndroid,
  SiMaterialdesign,
  SiRailway,
  SiVercel,
  SiLucide,
  SiSqlalchemy,
  SiPydantic,
  SiShadcnui,
  SiPostgresql
} from "react-icons/si";

export interface ProjectTheme {
  primaryColor: string;     // Hex color code (e.g. #10B981)
  accentText: string;       // Tailwind class for accented text
  bgGlow: string;           // Tailwind class for glowing backgrounds
  borderMuted: string;      // Tailwind class for subtle borders
  borderActive: string;      // Tailwind class for highlighted borders
  gradient: string;          // Tailwind gradient from top/bottom to transparent
  shadow: string;            // Tailwind shadow color
  iconName: string;          // Lucide icon component name
  imageSrc: string;          // Project banner image URL
}

// Detailed brand background, text color, and icon configuration for solid badges
export const skillDetails: Record<string, { icon: any; bg: string; text: string; border?: string }> = {
  "HTML": { icon: SiHtml5, bg: "bg-[#E34F26]", text: "text-white" },
  "CSS": { icon: SiCss, bg: "bg-[#1572B6]", text: "text-white" },
  "JavaScript": { icon: SiJavascript, bg: "bg-[#F7DF1E]", text: "text-black" },
  "React": { icon: FaReact, bg: "bg-[#61DAFB]", text: "text-black" },
  "React.js": { icon: FaReact, bg: "bg-[#61DAFB]", text: "text-black" },
  "Next.js": { icon: SiNextdotjs, bg: "bg-[#000000]", text: "text-white", border: "border-white/20" },
  "Next.js 14": { icon: SiNextdotjs, bg: "bg-[#000000]", text: "text-white", border: "border-white/20" },
  "Next.js 15": { icon: SiNextdotjs, bg: "bg-[#000000]", text: "text-white", border: "border-white/20" },
  "Tailwind CSS": { icon: SiTailwindcss, bg: "bg-[#06B6D4]", text: "text-white" },
  
  "Node.js": { icon: FaNodeJs, bg: "bg-[#339933]", text: "text-white" },
  "Express.js": { icon: SiExpress, bg: "bg-[#000000]", text: "text-white", border: "border-white/25" },
  "Express": { icon: SiExpress, bg: "bg-[#000000]", text: "text-white", border: "border-white/25" },
  "REST APIs": { icon: SiSwagger, bg: "bg-[#0052CC]", text: "text-white" },
  "MySQL": { icon: SiMysql, bg: "bg-[#00758F]", text: "text-white" },
  "MySQL 8.0": { icon: SiMysql, bg: "bg-[#00758F]", text: "text-white" },
  "MongoDB": { icon: SiMongodb, bg: "bg-[#47A248]", text: "text-white" },
  "MongoDB Atlas": { icon: SiMongodb, bg: "bg-[#47A248]", text: "text-white" },
  
  "Docker": { icon: FaDocker, bg: "bg-[#2496ED]", text: "text-white" },
  "Containerized deployment": { icon: FaDocker, bg: "bg-[#2496ED]", text: "text-white" },
  "Kubernetes": { icon: SiKubernetes, bg: "bg-[#326CE5]", text: "text-white" },
  "@kubernetes/client-node": { icon: SiKubernetes, bg: "bg-[#326CE5]", text: "text-white" },
  "Jenkins": { icon: SiJenkins, bg: "bg-[#D24939]", text: "text-white" },
  "GitHub Actions": { icon: SiGithubactions, bg: "bg-[#000000]", text: "text-white", border: "border-white/20" },
  "AWS EC2": { icon: FaAws, bg: "bg-[#FF9900]", text: "text-white" },
  "AWS IAM": { icon: FaAws, bg: "bg-[#232F3E]", text: "text-white" },
  "RabbitMQ": { icon: SiRabbitmq, bg: "bg-[#FF6600]", text: "text-white" },
  "Grafana": { icon: SiGrafana, bg: "bg-[#F46800]", text: "text-white" },
  
  "Git": { icon: SiGit, bg: "bg-[#000000]", text: "text-white", border: "border-white/20" },
  "GitHub": { icon: FaGithub, bg: "bg-[#181717]", text: "text-white", border: "border-white/20" },
  "Postman": { icon: SiPostman, bg: "bg-[#FF6C37]", text: "text-white" },
  "PostgreSQL": { icon: SiPostgresql, bg: "bg-[#4169E1]", text: "text-white" },
  "GeoLite2": { icon: FaGlobe, bg: "bg-[#3182CE]", text: "text-white" },
  "Python": { icon: FaPython, bg: "bg-[#3776AB]", text: "text-white" },
  "Python 3.11+": { icon: FaPython, bg: "bg-[#3776AB]", text: "text-white" },
  "Java": { icon: FaJava, bg: "bg-[#B07219]", text: "text-white" },
  "JavaFX": { icon: FaJava, bg: "bg-[#B07219]", text: "text-white" },
  "C++": { icon: SiCplusplus, bg: "bg-[#00599C]", text: "text-white" },
  "C": { icon: SiC, bg: "bg-[#00599C]", text: "text-white" },
  "Hugging Face": { icon: SiHuggingface, bg: "bg-[#FFD21E]", text: "text-black" },
  "Sentence Transformers": { icon: SiHuggingface, bg: "bg-[#FFD21E]", text: "text-black" },

  // Project Stack Mappings
  "TypeScript": { icon: SiTypescript, bg: "bg-[#3178C6]", text: "text-white" },
  "Bun": { icon: SiBun, bg: "bg-[#FBF0DF]", text: "text-black", border: "border-[#E8D4BA]" },
  "Clerk": { icon: SiClerk, bg: "bg-[#6C47FF]", text: "text-white" },
  "Stripe": { icon: SiStripe, bg: "bg-[#635BFF]", text: "text-white" },
  "Solidity": { icon: SiSolidity, bg: "bg-[#363636]", text: "text-white" },
  "FastAPI": { icon: SiFastapi, bg: "bg-[#009688]", text: "text-white" },
  "Maven": { icon: SiApachemaven, bg: "bg-[#C71A36]", text: "text-white" },
  "Kotlin": { icon: SiKotlin, bg: "bg-[#7F52FF]", text: "text-white" },
  "Vite": { icon: SiVite, bg: "bg-[#646CFF]", text: "text-white" },
  "Framer Motion": { icon: SiFramer, bg: "bg-[#0055FF]", text: "text-white" },
  "React Router": { icon: SiReactrouter, bg: "bg-[#CA4245]", text: "text-white" },
  "Redis": { icon: SiRedis, bg: "bg-[#DC382D]", text: "text-white" },
  "Socket.io": { icon: SiSocketdotio, bg: "bg-[#010101]", text: "text-white", border: "border-white/20" },
  "Gemini API": { icon: SiGooglegemini, bg: "bg-[#8E75C8]", text: "text-white" },
  "Sanity CMS": { icon: SiSanity, bg: "bg-[#F03E2F]", text: "text-white" },
  "Chrome Extension Manifest V3": { icon: SiGooglechrome, bg: "bg-[#4285F4]", text: "text-white" },
  "Jetpack Compose": { icon: SiAndroid, bg: "bg-[#3DDC84]", text: "text-black" },
  "Material 3": { icon: SiMaterialdesign, bg: "bg-[#757575]", text: "text-white" },
  "Railway": { icon: SiRailway, bg: "bg-[#131313]", text: "text-white", border: "border-white/20" },
  "Vercel": { icon: SiVercel, bg: "bg-[#000000]", text: "text-white", border: "border-white/20" },
  "Lucide Icons": { icon: SiLucide, bg: "bg-[#F97316]", text: "text-white" },
  "SQLAlchemy": { icon: SiSqlalchemy, bg: "bg-[#E2E8F0]", text: "text-black" },
  "Pydantic": { icon: SiPydantic, bg: "bg-[#E92063]", text: "text-white" },
  "shadcn/ui": { icon: SiShadcnui, bg: "bg-[#000000]", text: "text-white", border: "border-white/20" },
  "Recharts": { icon: FaChartLine, bg: "bg-[#2563EB]", text: "text-white" },
  "Chart.js / Recharts": { icon: FaChartLine, bg: "bg-[#2563EB]", text: "text-white" },

  // Newly mapped custom tags
  "Sandbox execution model": { icon: FaMicrochip, bg: "bg-[#1E1F22]", text: "text-white" },
  "Monaco Editor": { icon: FaCode, bg: "bg-[#007ACC]", text: "text-white" },
  "Winston logging": { icon: FaFileAlt, bg: "bg-[#1C1C1E]", text: "text-white/90", border: "border-white/10" },
  "Web Speech API": { icon: FaMicrophone, bg: "bg-[#0070F3]", text: "text-white" },
  "localStorage": { icon: FaDatabase, bg: "bg-[#F39C12]", text: "text-white" },
  "Responsive UI": { icon: FaMobileAlt, bg: "bg-[#3498DB]", text: "text-white" },
  "Accessibility-first design": { icon: FaUniversalAccess, bg: "bg-[#2ECC71]", text: "text-white" },
  "TF-IDF Vectorizer": { icon: FaBrain, bg: "bg-[#8E44AD]", text: "text-white" },
  "DBSCAN": { icon: FaProjectDiagram, bg: "bg-[#1ABC9C]", text: "text-white" },
  "Room": { icon: FaDatabase, bg: "bg-[#4285F4]", text: "text-white" },
  "Hilt": { icon: FaPlug, bg: "bg-[#00E676]", text: "text-black" },
  "Coroutines": { icon: FaSyncAlt, bg: "bg-[#7F52FF]", text: "text-white" },
  "Flow / StateFlow": { icon: FaStream, bg: "bg-[#3F51B5]", text: "text-white" },
  "MVVM": { icon: FaSitemap, bg: "bg-[#9C27B0]", text: "text-white" },
  "Clean Architecture": { icon: FaShieldAlt, bg: "bg-[#607D8B]", text: "text-white" },
  "IP detection API": { icon: FaGlobe, bg: "bg-[#E74C3C]", text: "text-white" }
};

export const DEFAULT_THEME: ProjectTheme = {
  primaryColor: "#E1E0CC",
  accentText: "text-[#E1E0CC]",
  bgGlow: "bg-[#E1E0CC]/5",
  borderMuted: "border-[#E1E0CC]/10",
  borderActive: "hover:border-[#E1E0CC]/40",
  gradient: "from-[#E1E0CC]/10 via-neutral-950 to-neutral-950",
  shadow: "shadow-[#E1E0CC]/20",
  iconName: "Code",
  imageSrc: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop",
};
